export default function Head() {
  return (
    <>
      <title>Todo Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/icons8-todo-list-16.png" />
    </>
  );
}
