import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import Provider from "./Provider";
// import {mode} from "./ToggleTheme";

// import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        {/* <div className=" dark:bg-slate-900  dark:text-white bg-gray-400 "> */}
        <Provider>
          <Header />
          {children} <Footer />
          {/* </div> */}
        </Provider>
      </body>
    </html>
  );
}
