import Navbar from "@/components/sections/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/sections/Footer";
import Providers from "@/components/sections/provider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

//  export let metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userId = cookies().get("user_id")?.value;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar userId={userId} />
          <main className="px-8">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
