import Navbar from "@/components/sections/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/sections/Footer";
import Providers from "@/components/sections/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="px-8">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
