import Navbar from "@/components/Navbar";
import Head from "next/head";
import Footer from "@/components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favi.png" />
      </Head>
      <div>
        <Navbar />
        <Footer />
      </div>
    </>
  );
}
