import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
// import { ThemeProvider } from "next-themes";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ThemeProvider enableSystem={true} attribute="class">
    <html lang="en">
      <body>
        {" "}
        <Header />
        {children} <Footer />
      </body>
    </html>
    // </ThemeProvider>
  );
}
